name: Merged to main
on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    name: Pull main into open PRs
    runs-on: ubuntu-18.04
    steps:
      - name: AutoUpdate
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          # needs GitHub PAT so that workflows are triggered as result of commits from auto update.
          GITHUB_TOKEN: "${{ secrets.MY_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate,keep up-to-date"
          EXCLUDED_LABELS: "dependencies,wontfix"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
