name: Pull request to main
on:
  pull_request:
    branches:
      - main

concurrency:
  group: "pp100"

jobs:
  automerge:
    name: Enable AutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: Enable AutoMerge on PR
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          # must be classic to have GraphQL permissions
          github-token: ${{ secrets.MY_CLASSIC_TOKEN }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "guilherme-ptml"

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE

  test-pp100:
    name: Test pp100
    runs-on: ubuntu-latest
    steps:
      - name: Running pp100
        shell: pwsh
        run: |
          Start-Sleep -Seconds 10
