name: Pull request to main
on:
  pull_request:
    branches:
      - main

concurrency:
  group: "pp100"

jobs:
  automerge:
    name: Enable AutoMerge
    runs-on: ubuntu-latest
    steps:
      - name: Enable AutoMerge on PR
        uses: daneden/enable-automerge-action@v1
        with:
          # A personal access token that you have generated and saved in the
          # repo or org’s encrypted secrets
          # must be classic to have GraphQL permissions
          github-token: ${{ secrets.MY_CLASSIC_TOKEN }}

          # The name of the PR author to enable automerge for
          # Defaults to dependabot[bot]
          allowed-author: "guilherme-ptml,jonathandaza"

          # Allowed values: MERGE | SQUASH | REBASE
          # Defaults to MERGE
          merge-method: MERGE

  run-cypress:
    name: 🤖 Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Cypress tests BFF
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5

  build-bff:
    name: 🤗 Build & unit test BFF
    runs-on: ubuntu-latest
    steps:
      - name: Build & unit test BFF
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5

  run-functional-automation:
    name: 🔬 Functional tests
    runs-on: ubuntu-latest
    steps:
      - name: Functional tests
        shell: pwsh
        run: |
          Start-Sleep -Seconds 5

  functional-tests-passed:
    name: 🎉 Functional tests all passed
    needs: [run-functional-automation]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'All functional tests passed'
        shell: bash

  test-pp100:
    name: Test pp100
    runs-on: ubuntu-latest
    steps:
      - name: Running pp100
        shell: pwsh
        run: |
          Start-Sleep -Seconds 30
